name: Deploy Say Hello Application
on:
 workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: checkout contents from repository
     uses: actions/checkout@v3
   - name: install java
     uses: actions/setup-java@v3
     with:
       java-version: 17
       distribution: 'zulu'
   - name: caching
     uses: actions/cache@v3
     with:
      path: /.m2
      key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
      restore-keys: ${{runner.os}}-maven
   - name: get maven
     run: |
       cd hello/
       mvn clean package
   - name: list file names
     run: |
       cd hello/target/
       ls -al
   - name: deploy jar file
     uses: azure/webapps-deploy@v2
     with:
      app-name: test-azure-webapp
      publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
      package: hello/target/hello-0.0.1-SNAPSHOT.jar
